1.) db.people.insertOne({first_name: "Jacob", last_name: "Coffey", email: "jacob23.coffey@gmail.com", gender: "Male", age: 25, state: "Michigan", children: []})
2.) db.people.insertOne({first_name: "Tammy", last_name: "Coffey", email: "tammycoffey11@gmail.com", gender: "Female", age: 55, state: "Michigan", children: {name: "Joshua", age: 22}, {name: "Heather", age: 34}})
3.) db.people.updateOne({first_name: "Clarence"}, { $set: {state: "South Dakota"}})
4.) db.people.updateOne({ $and: [{first_name: "Rebecca"}, {last_name: "Hayes"}]}, {$unset: {email: 1}})
5.) db.people.updateMany({state: "Missouri"}, {$inc: {age: 1}})
6.) db.people.replaceOne({$and: [{first_name: "Jerry"}, {last_name: "Baker"}]}, { first_name: "Jerry", last_name: "Baker-Mendez", email: "jerry@classic.ly", gender:"Male", age: 28, state: "Vermont", "children": [{name: "Alan", age: 18}, {name: "Jenny", age: 3}] })
7.) db.people.deleteOne({$and: [{first_name: "Wanda"}, {last_name: "Bowman"}]})
8.) db.people.deleteMany({email: undefined})
9.a) db.submissions.insertOne({title: "The River Bend", upvotes: 10, downvotes: 2, artist: "6369b308c13b2b1ce42506e1"})
9.b) db.submissions.insertOne({title: "Ninve Lives", upvotes: 7, downvotes: 0, artist: "6369b308c13b2b1ce425070f"})
9.c) db.submissions.insertOne({title: "Star Bright", upvotes: 19, downvotes: 5, artist: "6369b308c13b2b1ce4250792"})
9.d) db.submissions.insertOne({title: "Why Like This?", upvotes: 1, downvotes: 5, artist: "6369b308c13b2b1ce4250718"})
9.e) db.submissions.insertOne({title: "Non Sequitur", upvotes: 11, downvotes: 1, artist: "6369b308c13b2b1ce42506df"})
10.) db.submissions.updateOne({title: "The River Bend"}, {$inc: {upvotes: 2}})
11.) db.submissions.updateMany({upvotes: {$gte: 10}}, {$set: {round2: true}})